DELETE http://localhost:3001/api/v1/users/58
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjU4LCJlbWFpbCI6ImZlamltMTg4QGdtYWlsLmNvbSIsInJvbGUiOiJ0aWNrZXRQdXJjaGFzZXIiLCJpYXQiOjE3Mjk0NTAyNDIsImV4cCI6MTcyOTQ1Mzg0MiwiYXVkIjoibG9jYWxob3N0OjMwMDEiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMSJ9.6xEp1r0jVjmQ2gmiq720eWlM9cw7Uu0g6_sAR8ecRcQ