GET http://localhost:3001/users/58/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjU4LCJlbWFpbCI6ImZlamltMTg4QGdtYWlsLmNvbSIsInJvbGUiOiJ0aWNrZXRQdXJjaGFzZXIiLCJpYXQiOjE3MjkyNjIyMTgsImV4cCI6MTcyOTI2NTgxOCwiYXVkIjoibG9jYWxob3N0OjMwMDEiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMSJ9.6oETUjJP1qN3E6I9S-WviKYnQ7BBQaUpXJd-16Fm_HE